import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Speed Test",
  description: "Most accurate speed test",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* SEO Meta Tags */}
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Most accurate speed test" />
        <meta name="robots" content="index, follow" />

        <title>Speed Test</title>

        {/* Adsterra & Other Ad Scripts */}
        <Script
          src="//pl27104063.profitableratecpm.com/1a/f9/aa/1af9aad165e25b82433d54595e72659e.js"
          strategy="afterInteractive"
        />
        <Script
          async
          data-cfasync="false"
          src="//pl27104175.profitableratecpm.com/ad963ca5988e85713a41b39cb63d99a0/invoke.js"
          strategy="afterInteractive"
        />
      
        <Script
          src="https://fpyf8.com/88/tag.min.js"
          data-zone="155783"
          async
          data-cfasync="false"
          strategy="afterInteractive"
        />
        <Script
          src="//pl27108278.profitableratecpm.com/3c/b1/48/3cb148206b9957707c11312340239933.js"
          strategy="afterInteractive"
        />

        {/* Google Analytics */}
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-5NY3DGDM0M"
          strategy="afterInteractive"
        />
        <Script id="gtag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-5NY3DGDM0M');
          `}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
          {children}
      </body>
    </html>
  );
}


// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Script from "next/script";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Speed Test",
//   description: "Most accurate speed test",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head>
//         {/* SEO Meta Tags */}
//         <meta charSet="UTF-8" />
//         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
//         <meta name="description" content="Most accurate speed test" />
//         <meta name="robots" content="index, follow" />

//         <title>Speed Test</title>
//         <script
//           type="text/javascript"
//           src="//pl27104063.profitableratecpm.com/1a/f9/aa/1af9aad165e25b82433d54595e72659e.js"
//         ></script>
//         <script
//           async="async"
//           data-cfasync="false"
//           src="//pl27104175.profitableratecpm.com/ad963ca5988e85713a41b39cb63d99a0/invoke.js"
//         ></script>
//         <script
//           type="text/javascript"
//           src="//pl27104063.profitableratecpm.com/1a/f9/aa/1af9aad165e25b82433d54595e72659e.js"
//         ></script>
//         {/* Google Analytics */}
//         <script
//           async
//           src="https://www.googletagmanager.com/gtag/js?id=G-5NY3DGDM0M"
//         ></script>
//         <Script id="gtag-init" strategy="afterInteractive">
//           {`
//             window.dataLayer = window.dataLayer || [];
//             function gtag(){dataLayer.push(arguments);}
//             gtag('js', new Date());
//             gtag('config', 'G-5NY3DGDM0M');
//           `}
//         </Script>
//         <script
//           src="https://fpyf8.com/88/tag.min.js"
//           data-zone="155783"
//           async
//           data-cfasync="false"
//         ></script>
//       </head>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <div id="container-ad963ca5988e85713a41b39cb63d99a0">{children}</div>
//       </body>
//     </html>
//   );
// }

// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }
